[project]
name = "music-intelligence"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipdb>=0.13.13",
    "ipython>=9.10.0",
    "maturin>=1.12.3",
    "numpy>=2.4.2",
    "plotly>=6.5.2",
]
